git:
  depth: 1
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - npm run docs
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
