queue_rules:
  - name: default
    # speculative_checks: 3
    # batch_size: 2
    conditions:
      - check-success=Build (test)
      - check-success=Test (yarn test)
pull_request_rules:
  - name: update out-of-sync PR
    conditions:
      - base=master
      - -conflict
      - -draft
    actions:
      update:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: close stale pull request
    conditions:
      - base=master
      - -closed
      - updated-at<14 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it is a mistake.
  - name: merge Renovate pull request
    conditions:
      - author=renovate[bot]
      - label=dependency-update
      - label!=major
    actions:
      review:
        type: APPROVE
        message: Automatically approving Renovate
      queue:
        name: default
        method: rebase
        priority: low
  - name: close Renovate pull request (conflict)
    conditions:
      - conflict
      - author=renovate[bot]
      - label=dependency-update
    actions:
      close:
        message: |
          This automated pull request has a conflict. Closing - Renovate will create a new PR.
