language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
  - yarn global add codecov codacy-coverage
script:
  - yarn test --coverage
  - yarn build
after_success:
  - codecov
  - cat ./coverage/lcov.info | codacy-coverage
cache:
  yarn: true
  directories:
    - "node_modules"
notifications:
  email:
    on_success: never
    on_failure: always
